---
- name: Configure netatalk
  ansible.builtin.blockinfile:
    path: /etc/netatalk/afp.conf
    block: |
      [timecapsule]
      path = {{ timecapsule_mount_point }}
      time machine = yes
      valid users = @{{ timecapsule_user }}
      unix priv = no
