---
- name: Get timecapsule_user user information
  ansible.builtin.user:
    name: "{{ timecapsule_user }}"
  register: timecapsule_user_info

- name: Set UID and GID facts for timecapsule_user
  ansible.builtin.set_fact:
    timecapsule_user_uid: "{{ timecapsule_user_info.uid }}"
    timecapsule_user_gid: "{{ timecapsule_user_info.group }}"
