---
- name: Check device
  ansible.builtin.import_tasks: check_device.yml
- name: Install dependencies
  ansible.builtin.import_tasks: install_dependencies.yml
- name: Gather user information
  ansible.builtin.import_tasks: gather_user_info.yml
- name: Format disk to exFAT
  ansible.builtin.import_tasks: format_disk_exfat.yml
- name: Configure automount
  ansible.builtin.import_tasks: configure_automount.yml
- name: Configure Netatalk
  ansible.builtin.import_tasks: configure_netatalk.yml
- name: Enable restart script
  ansible.builtin.import_tasks: enable_restart_script.yml
