---
- name: Check device
  ansible.builtin.import_tasks: check_device.yml
- name: Check dependencies
  ansible.builtin.import_tasks: check_dependencies.yml
- name: Gather user information
  ansible.builtin.import_tasks: gather_user_info.yml
- name: Format disk to exFAT
  ansible.builtin.import_tasks: format_disk_exfat.yml
- name: Configure automount
  ansible.builtin.import_tasks: configure_automount.yml
- name: Configure Netatalk
  ansible.builtin.import_tasks: configure_netatalk.yml
- name: Enable restart script
  ansible.builtin.import_tasks: enable_restart_script.yml

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ picapsule_dependencies }}"
    state: present

- name: Create mount point
  ansible.builtin.file:
    path: "{{ picapsule_mount_point }}"
    state: directory
    owner: "{{ picapsule_user }}"
    group: "{{ picapsule_user }}"

- name: Mount device
  ansible.builtin.mount:
    path: "{{ picapsule_mount_point }}"
    src: "/dev/{{ picapsule_device }}"
    fstype: exfat
    state: mounted
